name: Build and Deploy pumpkin-fe to Docker Hub and update tag in infra repo

on:
  push:
    branches: [ "main" ]
    paths:
      - "fe/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "fe/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./fe
          file: ./fe/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pumpkin-fe:${{ github.sha }}

      # 1. Securely pull the infra repository using your existing PAT secret
      - name: Checkout pumpkin_infra repo
        uses: actions/checkout@v4
        with:
          repository: 'elvish-ishaan/pumpkin_infra'
          token: ${{ secrets.PAT }}
          path: pumpkin_infra

      # 2. Navigate to helm/fe, swap the tag, and push back
      - name: Update tag and push to infra repo
        run: |
          cd pumpkin_infra/helm/fe
          echo "inside fe directory"
          
          # Update image tag in values.yaml
          sed -i "s|tag: .*|tag: \"${{ github.sha }}\"|g" values.yaml
          echo "updated the image tag"

          # Commit and push changes safely
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add values.yaml
          git commit -m "Update pumpkin-fe image to ${{ github.sha }}"
          git push